config:
  auth_key: "authkey"
  torrent_pass: "torrentpass"
  owner_nick: "MyNick"
  bot_nick: "Astrid"
  download_path: "/path/to/my/watch/folder/"
  series:
    dexter: "dexter"
    big_bang_theory: "big bang"
    two_and_half: "two and a half"
    csi: "csi"
    himym: "how i met your mother"
    ltm: "lie to me"
    ncis: "ncis"
    scrubs: "scrubs"
    dirty_jobs: "dirty jobs"
    csi: "csi"
    mb: "mythbuster"
    cm: "criminal minds"
    dollhouse: "dollhouse"
    crash: "crash"